services:
  api:
    container_name: rumosaudavel-api
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "9443:9443"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - rumosaudavel_network

networks:
  rumosaudavel_network:
    external: true